# Generated by Django 3.2.4 on 2021-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210617_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CONSUMER', 'Consumer'), ('CREATOR', 'Creator')], default='CONSUMER', max_length=50, verbose_name='Type'),
        ),
    ]
