# Generated by Django 3.2.4 on 2021-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumermore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creatormore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='console',
            field=models.CharField(choices=[('PC', 'Pc'), ('PLAYSTATION', 'Playstation'), ('XBOX', 'Xbox'), ('OTHERS', 'Others')], default='PC', max_length=50, verbose_name='Console'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='hours_played',
            field=models.IntegerField(default=0, verbose_name='Hours Played'),
        ),
        migrations.AddField(
            model_name='user',
            name='pictures',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='ConsumerMore',
        ),
        migrations.DeleteModel(
            name='CreatorMore',
        ),
    ]
