# Generated by Django 3.2.4 on 2021-06-24 11:58

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210624_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Creator'},
        ),
        migrations.AlterModelManagers(
            name='consumer',
            managers=[
                ('objects', accounts.models.ConsumerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='creator',
            managers=[
                ('objects', accounts.models.CreatorManager()),
            ],
        ),
        migrations.AlterField(
            model_name='creator',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='id/description-images/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.creator')),
            ],
        ),
    ]
