# Generated by Django 3.2.4 on 2021-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210624_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='id/avatar/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
