# Generated by Django 3.2.4 on 2021-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210714_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CONSUMER', 'Consumer'), ('CREATOR', 'Creator')], default='CONSUMER', max_length=50, verbose_name='Type'),
        ),
    ]
