# Generated by Django 3.2.4 on 2021-08-13 12:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='game',
        ),
        migrations.AlterField(
            model_name='creator',
            name='console',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PC', 'Pc'), ('PLAYSTATION', 'Playstation'), ('XBOX', 'Xbox'), ('OTHERS', 'Others')], default='PC', max_length=50, verbose_name='Console'), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='dafault.jpg', upload_to='media/avatar'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
